import { IBM_Plex_Sans_KR, Hahmlet } from "next/font/google";

import localFont from "next/font/local";

import "./globals.css";

const IBM = IBM_Plex_Sans_KR({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-IBM",
});

const Hahm = Hahmlet({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-hahmlet",
});

const pretendard = localFont({
  src: "./fonts/Pretendard-Medium.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="kr">
      <body
        className={`${pretendard.variable} ${Hahm.variable} ${IBM.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
